config/routes.rb
Rails.application.routes.draw do
  resources :species

end

app/models/species.rb
class Species < ActiveRecord::Base

  # Return a status string of a particular species
  def full_species
    "#{name} #{identification} has#{(assimilated? ? ' ' : ' not ')}been assimilated."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]

  # GET /species
  # GET /species.json
  def index
    @species = Species.all
  end

  # GET /species/1
  # GET /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species.destroy
    respond_to do |format|
      format.html { redirect_to species_index_url, notice: 'Species was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def species_params
      params.require(:species).permit(:name, :identification, :assimilated)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Progeny</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/species/_form.html.erb
<%= form_for(@species) do |f| %>
  <% if @species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
      <% @species.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :identification %><br>
    <%= f.number_field :identification %>
  </div>
  <div class="field">
    <%= f.label :assimilated %><br>
    <%= f.check_box :assimilated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/species/edit.html.erb
<h1>Editing Species</h1>

<%= render 'form' %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

app/views/species/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Species</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Identification</th>
      <th>Assimilated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @species.each do |species| %>
      <tr>
        <td><%= species.name %></td>
        <td><%= species.identification %></td>
        <td><%= species.assimilated %></td>
        <td><%= link_to 'Show', species %></td>
        <td><%= link_to 'Edit', edit_species_path(species) %></td>
        <td><%= link_to 'Destroy', species, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Species', new_species_path %>

app/views/species/new.html.erb
<h1>New Species</h1>

<%= render 'form' %>

<%= link_to 'Back', species_index_path %>

app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @species.name %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @species.identification %>
</p>

<p>
  <strong>Assimilated:</strong>
  <%= @species.assimilated %>
</p>

<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_index_path %>